old/protected/controllers/OrderController.php
<?php

class OrderController extends Controller
{

    public function actionPayLast($id)
    {
        $model = new ConfirmationForm();

        $order = $this->loadModel($id);
        if($order->status <> 10){
            throw new CHttpException(404,'The requested page does not exist.');
        }

        $bankAcc = BankAccount::model()->findAllByAttributes(array('status'=>EnumStatus::ACTIVE));
        if($bankAcc != null){
            $list = array();
            foreach($bankAcc as $acc){
                $list[$acc->kodeBankAccount] = '( '.$acc->bank->nama.' )'.$acc->norek.' - '.$acc->nama;
            }
        }

        if(isset($_POST['ConfirmationForm'])){
            $model->attributes = $_POST['ConfirmationForm'];

            $norek = '';
            $nama = '';
            $ba = BankAccount::model()->findByPk($model->kodeBankPenerima);
            if($ba != null){
                $norek = $ba->norek;
                $nama = $ba->nama;
            }

            if($model->validate()){
                $sql = "exec dbo.ProsesKonfirmasiPembayaranSisa '".$order->orderID."','".$model->total."','".$model->tanggal."','".$model->tanggalTerima."','".$model->kodeBank."','".$model->norekPengirim."','".$model->namaPengirim."','".$model->kodeBankPenerima."','".$norek."','".$nama."'";
                // execute the sql command
                $exec =  Yii::app()->db->createCommand($sql);
                if($exec->execute()){
                    Yii::app()->user->setFlash('success','Success confirm last payment.');
                    $this->redirect(Yii::app()->homeUrl.'order');
                }
                else{
                    Yii::app()->user->setFlash('warning','Failed confirm last payment.');
                    $this->redirect(Yii::app()->homeUrl.'order');
                }
            }
        }

        $this->render('payLast', array(
            'model'=>$model,
            'list'=>$list,
        ));
    }

    public function actionConfirmation()
    {
        $model = new ListOrder();
        $model->status == 6 or $model->status == 10;
        $model->kodeMember = Yii::app()->user->id;

        $this->render('confirmation', array(
            'model'=>$model,
        ));
    }

    public function actionPay($id)
    {
        $model = new ConfirmationForm();

        $order = $this->loadModel($id);
        if($order->status <> 6){
            throw new CHttpException(404,'The requested page does not exist.');
        }

        $bankAcc = BankAccount::model()->findAllByAttributes(array('status'=>EnumStatus::ACTIVE));
        if($bankAcc != null){
            $list = array();
            foreach($bankAcc as $acc){
                $list[$acc->kodeBankAccount] = '( '.$acc->bank->nama.' )'.$acc->norek.' - '.$acc->nama;
            }
        }

        if(isset($_POST['ConfirmationForm'])){
            $model->attributes = $_POST['ConfirmationForm'];

            $norek = '';
            $nama = '';
            $ba = BankAccount::model()->findByPk($model->kodeBankPenerima);
            if($ba != null){
                $norek = $ba->norek;
                $nama = $ba->nama;
            }

            if($model->validate()){
                $sql = "exec dbo.ProsesKonfirmasiBill '".$order->orderID."','".$model->tanggal."','".Yii::app()->user->id."','".$model->total."','".$model->kodeBank."','".$model->norekPengirim."','".$model->namaPengirim."','".$model->kodeBankPenerima."','".$norek."','".$nama."'";
                // execute the sql command
                $exec =  Yii::app()->db->createCommand($sql);
                if($exec->execute()){
                    Yii::app()->user->setFlash('success','Success confirm payment.');
                    $this->redirect(Yii::app()->homeUrl.'order');
                }
                else{
                    Yii::app()->user->setFlash('warning','Failed confirm payment.');
                    $this->redirect(Yii::app()->homeUrl.'order');
                }
            }
        }

        $this->render('pay', array(
            'model'=>$model,
            'list'=>$list,
        ));
    }

    public function actionApprove($id){
        $model = $this->loadModel($id);

        $sql = "exec dbo.ProsesKonfirmasiOrder '".$model->orderID."','".$model->kodeToko."'";
        // execute the sql command
        $exec =  Yii::app()->db->createCommand($sql);
        if($exec->execute()){
            Yii::app()->user->setFlash('success','Success confirm order. Next step, pay downpayment bill.');
            $this->redirect(Yii::app()->homeUrl.'order');
        }
        else{
            Yii::app()->user->setFlash('warning','Failed confirm order.');
            $this->redirect(Yii::app()->homeUrl.'order');
        }
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        // sql query for calling the procedure
        $sql = "select* from dbo.ProductCategoryView where status = 1";
        // execute the sql command
        $category =  Yii::app()->db->createCommand($sql)->queryAll();

        $this->render('view',array(
            'category'=>$category,
            'model'=>$this->loadModel($id),
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer the ID of the model to be loaded
     */
    public function loadModel($id)
    {
        $model=ListOrder::model()->findByPk($id);
        if($model===null)
            throw new CHttpException(404,'The requested page does not exist.');
        return $model;
    }

    public function actionDelete($id)
    {
        $model = $this->loadModel($id);
        $model->status = 0;
        if($model->save()){
            EmailHelper::sendCancel($model->orderID);

            Yii::app()->user->setFlash('success','Success cancel order');
        }
        else{
            Yii::app()->user->setFlash('danger','Failed cancel order');
        }

        $this->redirect(Yii::app()->homeUrl.'order');
    }

    public function actionIndex(){

        $model = new ListOrder();
        $model->kodeMember = Yii::app()->user->id;

        $this->render('index', array(
            'model'=>$model,
        ));
    }

    public function actionCheckout($id){
        $model = ListOrder::model()->findByPk(array('orderID'=>$id, 'kodeMember'=>Yii::app()->user->id));
        if($model == null){
            Yii::app()->user->setFlash('info','Failed checkout. Not found!');
        }
        else{
            if($model->status <> 1){
                Yii::app()->user->setFlash('info','Failed checkout. Order invalid!');
            }
            else{
                $sql = "exec dbo.ProsesCheckout '".$model->orderID."'";
                // execute the sql command
                $exec =  Yii::app()->db->createCommand($sql);
                if($exec->execute()){
                    EmailHelper::sendToFactory($model->orderID);
                    EmailHelper::sendCheckout($model->orderID);

                    Yii::app()->user->setFlash('success','Success checkout');
                }
                else{
                    Yii::app()->user->setFlash('danger','Failed checkout');
                }
            }
        }

        $this->redirect(Yii::app()->homeUrl.'order');
    }

    public function actionCancel(){

        $model = new ListOrder();
        $model->status = 0;

        $this->render('cancel', array(
            'model'=>$model,
        ));
    }
}

old/protected/views/order/_search.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

    <div class="row form-row form-group">
        <div class="col-xs-2">
            <?php echo $form->label($model,'orderID'); ?>
        </div>
        <div class="col-xs-10">
            <div class="row">
                <div class="col-xs-6">
                    <?php echo $form->textField($model,'orderID',array('size'=>60,'maxlength'=>255)); ?>
                </div>
            </div>

        </div>
    </div>

    <div class="row form-row form-group">
        <div class="col-xs-2">
            <?php echo $form->label($model,'tanggal'); ?>
        </div>
        <div class="col-xs-10">
            <div class="row">
                <div class="col-xs-6">
                    <?php echo $form->textField($model,'tanggal'); ?>
                </div>
            </div>

        </div>
    </div>

    <div class="row form-row form-group">
        <div class="col-xs-2">
            <?php echo $form->label($model,'ip'); ?>
        </div>
        <div class="col-xs-10">
            <div class="row">
                <div class="col-xs-6">
                    <?php echo $form->textField($model,'ip',array('size'=>60,'maxlength'=>255)); ?>
                </div>
            </div>

        </div>
    </div>

    <div class="row form-row form-group">
        <div class="col-xs-2">
            <?php echo $form->label($model,'kodeMember'); ?>
        </div>
        <div class="col-xs-10">
            <div class="row">
                <div class="col-xs-6">
                    <?php echo $form->textField($model,'kodeMember',array('size'=>60,'maxlength'=>255)); ?>
                </div>
            </div>

        </div>
    </div>

    <div class="row form-row form-group">
        <div class="col-xs-2">
            <?php echo $form->label($model,'kodeToko'); ?>
        </div>
        <div class="col-xs-10">
            <div class="row">
                <div class="col-xs-6">
                    <?php echo $form->textField($model,'kodeToko',array('size'=>60,'maxlength'=>255)); ?>
                </div>
            </div>

        </div>
    </div>

    <div class="row form-row form-group">
        <div class="col-xs-2">
            <?php echo $form->label($model,'kodeKontener'); ?>
        </div>
        <div class="col-xs-10">
            <div class="row">
                <div class="col-xs-6">
                    <?php echo $form->textField($model,'kodeKontener',array('size'=>60,'maxlength'=>255)); ?>
                </div>
            </div>

        </div>
    </div>

    <div class="row form-row form-group">
        <div class="col-xs-2">
            <?php echo $form->label($model,'status'); ?>
        </div>
        <div class="col-xs-10">
            <div class="row">
                <div class="col-xs-6">
                    <?php echo $form->textField($model,'status'); ?>
                </div>
            </div>

        </div>
    </div>

	<div class="row buttons">
        <div class="col-xs-12">
            <?php echo CHtml::submitButton('Search'); ?>
    	</div>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

old/protected/views/order/cancel.php
<div class="row">
    <div class="col-sm-12">
        <h3 class="left">Canceled List Orders</h3>
        <div class="clear"></div>
        <hr />

        <?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
        <div class="search-form" style="display:none">
            <?php $this->renderPartial('_search',array(
                'model'=>$model,
            )); ?>
        </div><!-- search-form -->

        <?php $this->widget('zii.widgets.grid.CGridView', array(
            'id'=>'list-order-grid',
            'itemsCssClass'=>'table table-striped table-bordered table-hover',
            'dataProvider'=>$model->search(),
            'columns'=>array(
                'orderID',
                'tanggal',
                array(
                    'name'=>'kodeToko',
                    'value'=>'($data->toko != "" ? $data->toko->namaToko : "")',
                ),
                array(
                    'name'=>'kodeKontener',
                    'value'=>'($data->kontener != "" ? $data->kontener->nama : "")',
                ),
                array(
                    'name'=>'volume',
                    'value'=>'($data->kontener != "" ? $data->kontener->volume : "")',
                ),
                array(
                    'name'=>'status',
                    'value'=>'EnumOrder::getLabel($data->status)',
                ),
                array(
                    'class'=>'CButtonColumn',
                    'template'=>'{view}',
                    'buttons'=>array(
                        'view'=>array(
                            'imageUrl'=>false,
                            'label'=>'<i class="fa fa-search fa-fw"></i> View',
                            'options'=>array(
                                'class'=>'btn btn-info btn-xs',
                                'title'=>'View Detail',
                            ),
                        ),
                    ),
                ),
            ),
        )); ?>
    </div>
</div>

old/protected/views/order/confirmation.php
<div class="row">
    <div class="col-sm-12">
        <h3 class="left">Confirmation Order</h3>
        <div class="clear"></div>
        <hr />

        <div id="status-message">
            <?php if(Yii::app()->user->hasFlash('success')): ?>
                <div class="alert alert-success">
                    <?php echo Yii::app()->user->getFlash('success') ?>
                </div>
            <?php endif ?>

            <?php if(Yii::app()->user->hasFlash('info')): ?>
                <div class="alert alert-info">
                    <?php echo Yii::app()->user->getFlash('info') ?>
                </div>
            <?php endif ?>

            <?php if(Yii::app()->user->hasFlash('danger')): ?>
                <div class="alert alert-danger">
                    <?php echo Yii::app()->user->getFlash('danger') ?>
                </div>
            <?php endif ?>
        </div>

        <?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
        <div class="search-form" style="display:none">
            <?php $this->renderPartial('_search',array(
                'model'=>$model,
            )); ?>
        </div><!-- search-form -->

        <?php $this->widget('zii.widgets.grid.CGridView', array(
            'id'=>'list-order-grid',
            'itemsCssClass'=>'table table-striped table-bordered table-hover',
            'dataProvider'=>$model->search(),
            'columns'=>array(
                'orderID',
                'tanggal',
                array(
                    'name'=>'kodeToko',
                    'value'=>'($data->toko != "" ? $data->toko->namaToko : "")',
                ),
                array(
                    'name'=>'kodeKontener',
                    'value'=>'($data->kontener != "" ? $data->kontener->nama : "")',
                ),
                array(
                    'name'=>'volume',
                    'value'=>'($data->kontener != "" ? $data->kontener->volume : "")',
                ),
                array(
                    'name'=>'status',
                    'value'=>'EnumOrder::getLabel($data->status)',
                ),
                array(
                    'class'=>'CButtonColumn',
                    'template'=>'{view} {delete}',
                    'buttons'=>array(
                        'view'=>array(
                            'imageUrl'=>false,
                            'label'=>'<i class="fa fa-search fa-fw"></i> View',
                            'options'=>array(
                                'class'=>'btn btn-info btn-xs',
                                'title'=>'View Detail',
                            ),
                        ),
                        'delete'=>array(
                            'imageUrl'=>false,
                            'label'=>'<i class="fa fa-trash-o fa-fw"></i> Delete',
                            'options'=>array(
                                'class'=>'btn btn-danger btn-xs',
                                'title'=>'Delete',
                            ),
                            'visible'=>'$data->status == 1',
                        ),
                    ),
                ),
                array(
                    'class'=>'CButtonColumn',
                    'template'=>'{payDP} {pay}',
                    'buttons'=>array(
                        'payDP'=>array(
                            'imageUrl'=>false,
                            'label'=>'<i class="fa fa-edit fa-fw"></i> Confirm Payment Order',
                            'options'=>array(
                                'class'=>'btn btn-default btn-xs',
                                'title'=>'Confirm Payment Order',
                            ),
                            'visible'=>'$data->status == 6',
                            'url'=>'Yii::app()->createUrl("order/pay", array("id"=>$data->orderID))',
                        ),
                        'pay'=>array(
                            'imageUrl'=>false,
                            'label'=>'<i class="fa fa-money fa-fw"></i> Last Payment',
                            'options'=>array(
                                'class'=>'btn btn-default btn-xs',
                                'title'=>'Last Payment',
                            ),
                            'visible'=>'$data->status == 10',
                            'url'=>'Yii::app()->createUrl("order/payLast", array("id"=>$data->orderID))',
                        ),
                    ),
                ),
            ),
        )); ?>

    </div>
</div>

old/protected/views/order/index.php
<div class="row">
    <div class="col-sm-12">
        <h3 class="left">Order List</h3>
        <div class="clear"></div>
        <hr />

        <div id="status-message">
            <?php if(Yii::app()->user->hasFlash('success')): ?>
                <div class="alert alert-success">
                    <?php echo Yii::app()->user->getFlash('success') ?>
                </div>
            <?php endif ?>

            <?php if(Yii::app()->user->hasFlash('info')): ?>
                <div class="alert alert-info">
                    <?php echo Yii::app()->user->getFlash('info') ?>
                </div>
            <?php endif ?>

            <?php if(Yii::app()->user->hasFlash('danger')): ?>
                <div class="alert alert-danger">
                    <?php echo Yii::app()->user->getFlash('danger') ?>
                </div>
            <?php endif ?>
        </div>

        <?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
        <div class="search-form" style="display:none">
            <?php $this->renderPartial('_search',array(
                'model'=>$model,
            )); ?>
        </div><!-- search-form -->

        <?php $this->widget('zii.widgets.grid.CGridView', array(
            'id'=>'list-order-grid',
            'itemsCssClass'=>'table table-striped table-bordered table-hover',
            'dataProvider'=>$model->search(),
            'columns'=>array(
                'orderID',
                'tanggal',
                array(
                    'name'=>'kodeToko',
                    'value'=>'($data->toko != "" ? $data->toko->namaToko : "")',
                ),
                array(
                    'name'=>'kodeKontener',
                    'value'=>'($data->kontener != "" ? $data->kontener->nama : "")',
                ),
                array(
                    'name'=>'volume',
                    'value'=>'($data->kontener != "" ? $data->kontener->volume : "")',
                ),
                array(
                    'name'=>'status',
                    'value'=>'EnumOrder::getLabel($data->status)',
                ),
                array(
                    'class'=>'CButtonColumn',
                    'template'=>'{view}',
                    'buttons'=>array(
                        'view'=>array(
                            'imageUrl'=>false,
                            'label'=>'<i class="fa fa-search fa-fw"></i> View',
                            'options'=>array(
                                'class'=>'btn btn-info btn-xs',
                                'title'=>'View Detail',
                            ),
                        ),
                    ),
                ),
                array(
                    'class'=>'CButtonColumn',
                    'template'=>'{cancel} {checkout} {approve}',
                    'buttons'=>array(
                        'cancel'=>array(
                            'imageUrl'=>false,
                            'label'=>'<i class="fa fa-times fa-fw"></i> Cancel Order',
                            'options'=>array(
                                'class'=>'btn btn-warning btn-xs',
                                'title'=>'Cancel Order',
                            ),
                            'visible'=>'$data->status == 1',
                            'url'=>'Yii::app()->createUrl("order/delete", array("id"=>$data->orderID))',
                        ),
                        'checkout'=>array(
                            'imageUrl'=>false,
                            'label'=>'<i class="fa fa-search fa-fw"></i> Check Out',
                            'options'=>array(
                                'class'=>'btn btn-default btn-xs',
                                'title'=>'Check Out',
                            ),
                            'visible'=>'$data->status == 1',
                            'url'=>'Yii::app()->createUrl("order/checkout", array("id"=>$data->orderID))',
                        ),
                        'approve'=>array(
                            'imageUrl'=>false,
                            'label'=>'<i class="fa fa-check fa-fw"></i> Approve Order',
                            'options'=>array(
                                'class'=>'btn btn-primary btn-xs',
                                'title'=>'Approve Order',
                            ),
                            'visible'=>'$data->status == 3',
                            'url'=>'Yii::app()->createUrl("order/approve", array("id"=>$data->orderID))',
                        ),
                    ),
                ),
            ),
        )); ?>

    </div>
</div>

old/protected/views/order/pay.php
<div class="row">
    <div class="col-sm-12">
        <h3 class="left">Confirm Order</h3>
        <a href="<?php echo $this->createUrl('index'); ?>"><input type="button" class="btn btn-sm btn-info" value="List"></a>
        <div class="clear"></div>
        <hr />

        <div class="form">

            <?php $form=$this->beginWidget('CActiveForm', array(
                'id'=>'confirm-form',
                'enableAjaxValidation'=>false,
            )); ?>

            <div class="row form-row form-group">
                <div class="col-xs-2">
                    <?php echo $form->labelEx($model,'kodeBankPenerima'); ?>
                </div>
                <div class="col-xs-10">
                    <div class="row">
                        <div class="col-xs-6">
                            <?php echo $form->dropDownList($model,"kodeBankPenerima", $list,
                                array('class'=>'form-control', 'empty'=>'- Choose -')); ?>
                        </div>
                        <div class="col-xs-6">
                            <?php echo $form->error($model,'kodeBankPenerima'); ?>
                        </div>
                    </div>

                </div>
            </div>

            <hr>

            <div class="row form-row form-group">
                <div class="col-xs-2">
                    <?php echo $form->labelEx($model,'kodeBank'); ?>
                </div>
                <div class="col-xs-10">
                    <div class="row">
                        <div class="col-xs-6">
                            <?php echo $form->dropDownList($model,'kodeBank',
                                CHtml::listData(BankList::model()->findAllByAttributes(array('status'=>EnumStatus::ACTIVE)), 'kodeBank', 'nama'),
                                array('empty'=>'- Choose -', 'class'=>'form-control')); ?>
                        </div>
                        <div class="col-xs-6">
                            <?php echo $form->error($model,'kodeBank'); ?>
                        </div>
                    </div>

                </div>
            </div>

            <div class="row form-row form-group">
                <div class="col-xs-2">
                    <?php echo $form->labelEx($model,'norekPengirim'); ?>
                </div>
                <div class="col-xs-10">
                    <div class="row">
                        <div class="col-xs-6">
                            <?php echo $form->textField($model,'norekPengirim',array('class'=>'form-control','size'=>60,'maxlength'=>255)); ?>
                        </div>
                        <div class="col-xs-6">
                            <?php echo $form->error($model,'norekPengirim'); ?>
                        </div>
                    </div>

                </div>
            </div>

            <div class="row form-row form-group">
                <div class="col-xs-2">
                    <?php echo $form->labelEx($model,'namaPengirim'); ?>
                </div>
                <div class="col-xs-10">
                    <div class="row">
                        <div class="col-xs-6">
                            <?php echo $form->textField($model,'namaPengirim',array('class'=>'form-control','size'=>60,'maxlength'=>255)); ?>
                        </div>
                        <div class="col-xs-6">
                            <?php echo $form->error($model,'namaPengirim'); ?>
                        </div>
                    </div>

                </div>
            </div>

            <div class="row form-row form-group">
                <div class="col-xs-2">
                    <?php echo $form->labelEx($model,'tanggal'); ?>
                </div>
                <div class="col-xs-10">
                    <div class="row">
                        <div class="col-xs-6">
                            <?php echo $form->textField($model,'tanggal',array('class'=>'form-control date-picker','size'=>60,'maxlength'=>255)); ?>
                        </div>
                        <div class="col-xs-6">
                            <?php echo $form->error($model,'tanggal'); ?>
                        </div>
                    </div>

                </div>
            </div>

            <div class="row form-row form-group">
                <div class="col-xs-2">
                    <?php echo $form->labelEx($model,'total'); ?>
                </div>
                <div class="col-xs-10">
                    <div class="row">
                        <div class="col-xs-6">
                            <?php echo $form->textField($model,'total',array('class'=>'form-control','size'=>60,'maxlength'=>255)); ?>
                        </div>
                        <div class="col-xs-6">
                            <?php echo $form->error($model,'total'); ?>
                        </div>
                    </div>

                </div>
            </div>

            <input type="submit" class="btn btn-lg btn-primary" value="Save">

            <?php $this->endWidget(); ?>
        </div>
    </div>
</div>